name: co2_sensor_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  environment_sensors: ^0.2.0
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
